#!/bin/sh
set -e

if [ "$1" = "remove" ] && [ -d /run/systemd/system ]; then
    systemctl disable --now wireviewd.socket >/dev/null 2>&1 || true
    systemctl stop wireviewd.service >/dev/null 2>&1 || true
fi

exit 0
